# Generated by Django 5.1.6 on 2025-02-14 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_orderitem_product_alter_product_collection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="date",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 2, 14, 13, 53, 1, 655379, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="description",
            field=models.TextField(),
        ),
    ]
