# Generated by Django 5.1.5 on 2025-01-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_store_custo_first_n_8f83e0_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
                INSERT INTO store_collection (title) VALUES ('Bestsellers');
            """,
            """
                DELETE FROM store_collection WHERE title = 'Bestsellers';
            """
        )
    ]
